name: On Branch Push

on:
  push:
    branches:
      - fix/version-win-binary

jobs:
  publish-binaries-win:
    timeout-minutes: 20
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Go
        uses: actions/setup-go@v4
      
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      - name: Test script
        run: sh scripts/update_version.sh && cat conf/conf_prod.go
